CREATE TABLE LOP(
    MALOP VARCHAR(255) NOT NULL PRIMARY KEY ,
    TENLOP VARCHAR(255) NOT NULL,
    KHOAHOC INTEGER NOT NULL,
    GVCN VARCHAR(255) NOT NULL
);

INSERT INTO LOP(MALOP, TENLOP, KHOAHOC, GVCN) VALUES ('AT1', "AT16A", 1, "Nguyễn Văn Bình");
INSERT INTO LOP(MALOP, TENLOP, KHOAHOC, GVCN) VALUES ('AT2', "AT16B", 3, "Lê Thị Hồng");
INSERT INTO LOP(MALOP, TENLOP, KHOAHOC, GVCN) VALUES ('AT3', "AT16C", 2, "Nguyễn Hồng Hải");
INSERT INTO LOP(MALOP, TENLOP, KHOAHOC, GVCN) VALUES ('AT4', "AT16D", 4, "Trần Văn Hoàng");

CREATE TABLE HOSO(
    MAHS VARCHAR(255) NOT NULL PRIMARY KEY ,
    HOTEN VARCHAR(255) NOT NULL,
    NGAYSINH DATE,
    DIACHI VARCHAR(255) NOT NULL,
    LOP VARCHAR(255) NOT NULL,
    DIEMTOAN FLOAT,
    DIEMLY FLOAT,
    DIEMHOA FLOAT
);

INSERT INTO HOSO(MAHS, HOTEN, NGAYSINH, DIACHI, LOP, DIEMTOAN, DIEMLY, DIEMHOA) VALUES ('HS1', "ĐẶNG Thái Bình", "2001-10-27", "Quảng Ninh", "AT16E", 9, 8, 10);
INSERT INTO HOSO(MAHS, HOTEN, NGAYSINH, DIACHI, LOP, DIEMTOAN, DIEMLY, DIEMHOA) VALUES ('HS2', "Lê Bằng Nguyên", "2001-11-11", "Quảng Ninh", "AT16E", 9, 8, 10);
INSERT INTO HOSO(MAHS, HOTEN, NGAYSINH, DIACHI, LOP, DIEMTOAN, DIEMLY, DIEMHOA) VALUES ('HS3', "Nguyễn Quang Huy", "2001-8-6", "Quảng Ninh", "AT16D", 9, 8, 10);
INSERT INTO HOSO(MAHS, HOTEN, NGAYSINH, DIACHI, LOP, DIEMTOAN, DIEMLY, DIEMHOA) VALUES ('HS4', "Trần Văn Hoàng", "2000-5-4", "Argentina", "AT16E", 9, 8, 10);

